bad_words = [
    "bad_news",
    "arse",
    'arsehead',
    'arsehole',
    'ass',
    'asshole',
    'bastard',
    'bitch',
    'bloody',
    'bollocks',
    'brotherfucker',
    'bugger',
    'bullshit',
    'child-fucker'
    'christ on a bike',
    'christ on a cracker',
    'cock',
    'cocksucker',
    'crap',
    'cunt',
    'cum',
    'damn',
    'damn it',
    'dick',
    'dickhead',
    'dyke',
    'fatherfucker',
    'frigger',
    'fuck',
    'goddamn',
    'godsdamn',
    'hell',
    'holy shit',
    'horseshit',
    'in shit',
    'jesus Christ',
    'jesus fuck',
    'jesus H. Christ',
    'jesus Harold Christ',
    'jesus wept',
    'jesus, Mary and Joseph',
    'kike',
    'motherfucker',
    'nigga',
    'nigra',
    'piss',
    'prick',
    'pussy',
    'shit',
    'shit ass',
    'shite',
    'sisterfucker',
    'slut',
    'son of a bitch',
    'son of a whore',
    'spastic',
    'sweet Jesus',
    'turd',
    'twat',
    'wanker'
    'блядь',
    'дрочить',
    'ебать',
    'еблан',
    'ёб',
    'ёб твою мать',
    'иди на хуй',
    'на хуй',
    'недоумок',
    'охуеть',
    'охуенно',
    'пизда',
    'пиздато',
    'пиздец',
    'пошёл на хуй',
    'пошла на хуй',
    'пошли на хуй',
    'сука',
    'сучка',
    'сученок',
    'сучёнок',
    'твою мать',
    'ублюдок',
    'уебок',
    'уёбок',
    'хуй',
    'хуйня',
    'хер',
    'херня',
    'чмо',
]
